ServerName localhost

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined

DocumentRoot /usr/local/apache2/htdocs/

<Directory "/usr/local/apache2/htdocs/">
    Options FollowSymLinks
    AllowOverride All
    Require all granted

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.html [L]
</Directory>