ServerName localhost

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined

ProxyRequests Off
ProxyPreserveHost On

# Backend Kubernetes DNS direct
# IMPORTANT: pas de Define, on écrit direct

# ======================
# API BACKEND
# ======================
<Location /api/>
    ProxyPass http://backend.snapgram.svc.cluster.local:5000/
    ProxyPassReverse http://backend.snapgram.svc.cluster.local:5000/
    ProxyTimeout 60
</Location>

# ======================
# SOCKET.IO
# ======================
<Location /socket.io/>
    ProxyPass http://backend.snapgram.svc.cluster.local:5000/socket.io/
    ProxyPassReverse http://backend.snapgram.svc.cluster.local:5000/socket.io/
</Location>

# ======================
# UPLOADS
# ======================
<Location /uploads/>
    ProxyPass http://backend.snapgram.svc.cluster.local:5000/uploads/
    ProxyPassReverse http://backend.snapgram.svc.cluster.local:5000/uploads/
</Location>

# ======================
# REACT SPA
# ======================
DocumentRoot /usr/local/apache2/htdocs/

<Directory "/usr/local/apache2/htdocs/">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !^/api/
    RewriteCond %{REQUEST_URI} !^/socket.io/
    RewriteCond %{REQUEST_URI} !^/uploads/
    RewriteRule . /index.html [L]
</Directory>