version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: snapgram_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: snapgram
    volumes:
      - mongo_data:/data/db
    networks:
      - snapgram_net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.12
    container_name: snapgram_redis
    restart: unless-stopped
    networks:
      - snapgram_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongo:27017/snapgram
      REDIS_URL: redis://redis:6379
      JWT_SECRET: snapgram508
      CLIENT_URL: http://localhost
    volumes:
      - uploads_data:/app/uploads
    networks:
      - snapgram_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: snapgram_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - snapgram_net

volumes:
  mongo_data:
  uploads_data:

networks:
  snapgram_net:
    driver: bridge