apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: snapgram

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/PROJECT_ID/snapgram/snapgram-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000
              name: http

          env:
            - name: PORT
              value: "5000"

            - name: HOST
              value: "0.0.0.0"

            - name: MONGO_URI
              value: mongodb://mongo:27017/snapgram

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: snapgram-secrets
                  key: jwt-secret

            - name: CLIENT_URL
              value: "http://YOUR_DOMAIN"
              
            - name: CORS_ORIGIN
              value: "http://YOUR_DOMAIN"

            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_CLOUD_NAME

            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_KEY

            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_SECRET
            - name: REDIS_URL
              value: redis://redis.snapgram.svc.cluster.local:6379

          # Ajouter health check pour GCP
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: snapgram
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  