apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snapgram-ingress
  namespace: snapgram
  annotations:
    kubernetes.io/ingress.class: nginx

    # WebSocket support (CRITICAL)
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"

    # IMPORTANT for Socket.IO
    nginx.ingress.kubernetes.io/enable-websocket: "true"

spec:
  rules:
  - http:
      paths:

      # ======================
      # API
      # ======================
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000

      # ======================
      # SOCKET.IO
      # ======================
      - path: /socket.io/
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000

      # ======================
      # FRONTEND
      # ======================
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80