apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snapgram-ingress
  namespace: snapgram
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: snapgram-ip
spec:
  rules:
  - http:
      paths:

      # API REST
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000

      # Socket.IO (IMPORTANT)
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000