apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snapgram-ingress
  namespace: snapgram
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: snapgram-ip

    # important pour websocket + long polling
    ingress.gcp.kubernetes.io/timeout-sec: "3600"

spec:
  rules:
  - http:
      paths:

      - path: /socket.io/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend
            port:
              number: 5000

      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend
            port:
              number: 5000

      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend
            port:
              number: 80