name: CI/CD to GKE

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Authentification GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Setup gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # 4. Configurer Docker pour GCP
      - name: Configure Docker
        run: gcloud auth configure-docker

      # 5. Build backend image
      - name: Build & Push Backend
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest ./backend
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/backend:latest

      # 6. Build frontend image
      - name: Build & Push Frontend
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest ./frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/frontend:latest

      # 7. Récupérer cluster GKE
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials \
            ${{ secrets.GKE_CLUSTER }} \
            --zone ${{ secrets.GKE_ZONE }}

      # 8. Remplacer PROJECT_ID dans YAML (IMPORTANT)
      - name: Replace PROJECT_ID in k8s files
        run: |
          sed -i "s/PROJECT_ID/${{ secrets.GCP_PROJECT }}/g" k8s/backend.yaml
          sed -i "s/PROJECT_ID/${{ secrets.GCP_PROJECT }}/g" k8s/frontend.yaml

      # 9. Déployer sur Kubernetes
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment backend -n snapgram
          kubectl rollout restart deployment frontend -n snapgram